name: Frontend CI/CD with NCP

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Debug Environment Variables
        run: |
          echo "AWS_S3_BUCKET=${{ secrets.NCP_BUCKET_NAME }}"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.NCP_ACCESS_KEY }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.NCP_SECRET_KEY }}"

      - name: Upload to NCP Object Storage
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.NCP_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.NCP_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.NCP_SECRET_KEY }}
          # AWS_REGION: ${{ secrets.NCP_REGION }}
          AWS_ENDPOINT_URL: 'https://kr.object.ncloudstorage.com'
          SOURCE_DIR: 'dist' # 빌드된 디렉토리 (Vite, React 등 빌드 결과물 경로)
